on:
  pull_request:
    branches:
      - main
name: Validate JSON
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Controller JSON
        uses: dsanders11/json-schema-validate-action
        with:
          schema: .schema/controller.json
          files: "*/*/*/config.json"
